### ISSUE TITLE
missing parameter 'ilo_host'

### ISSUE THREAD

**Issue by ghost** [infinityworksltd/hpilo-exporter#13]
Hi,
I'm trying to use your hpilo-exporter and have run into and issue.

I have configured it as per your settings, but when I try and access the web page (http://prometheus:9416/metrics)  I get nothing on the web page, and the error "missing parameter 'ilo_host'" on the console of the server running the exporter.
If I use the full URL as in,
http://prometheus:9416/metrics?ilo_host=hpserver&ilo_port=443&ilo_user=administrator&ilo_password=mypassword
that works.
the hpilo-exporter is running on the same server as prometheus.

I'm starting the exporter like this:
hpilo-exporter --address=10.73.0.146 --port=9416 --endpoint="/metrics"

and the bottom of my prometheus.yml looks like this:
- job_name: 'hpilo'
  scrape_interval: 1m
  scrape_timeout: 30s
  params:
    ilo_host: ['hpserver']
    ilo_port: ['443']
    ilo_user: ['administrator']
    ilo_password: ['mypassword']
  static_configs:
    - targets:
      - hpserver

  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_ilo_host
    - source_labels: [__param_ilo_host]
      target_label: ilo_host
    - target_label: __address__
      replacement: prometheus:9416  # hpilo exporter.

**Comment by ghost** [comment]
i think you can fix this by making sure the exporter and everything it needs is compiled and setup in pythin 2.x

**Comment by saied-nawaz** [comment]
Looks like you solved your own problem maybe this would also help in the future #12
